receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
  loki:
    endpoint: http://loki:3100/api/prom/push
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [prometheusremotewrite, loki]
